### PR TITLE
Minor tweaks based on Bob's feedback

### PR DESCRIPTION
**Pull request by MartinHeroux**

### CODE REVIEW

**Comment by bbelderbos** [comment]
Nice, starts to look great, you happy? So you are working on some testing now right? 

What are the steps after that?

Btw, I am uploading karmabot to pypi today and I will share how to do that ...

**Comment by MartinHeroux** [comment]
Hi Bob,

I pushed some tests for the signal_processing mixin class; not done yet. 

However, I am happy with the current tests; they are a bit 'hacky'. I have a few ideas of what I might like to do, some of which might involve parametrization. But to be honest I am a bit lost when it comes to testing. I have no idea how thorough I should be. For example, should I also check to make sure my program throws the expected errors if function, method or class receives the wrong type of data? Also, Some books recommend one assert per test, while other say it is ok to have more than one, as long as the things being tested are related. Finally, I have ideas of how to test the signal processing mixin, but not too sure how to implement it. 

So if possible I would like to chat about testing. Brian Okken's book and others often explain how to write the tests and how to use the functionality of pytest, but I have yet to find a great resource that explains how to think about testing (what to test, what not to test, how much to test it), how best to approach it in a systematic way, and how to ensure the tests are maintainable. If you know of such a reference, I would be very greatful.

**Comment by MartinHeroux** [comment]
In terms of next steps (after I have finished and improved the tests), I think I have an MVP. I might like to test it out some more, and maybe have one of my colleagues try it out to see if there is something that is not intuitive or correct, and that can be improved.

I was thinking of including a way to batch process trials for a study, but I am not sure it would be worth the effort. Studies are so different from another and different research work in different ways. If I am going for a package that does one thing and does it well, then I have achieved this with the current version. Sure there might be some tweaks here and there, but the basics are there. The signal processing stuff is really a bonus, and will make the experience much nicer for non-coders and students. Also, the basic plotting capabilities is a nice addition.

I have wondered whether the .values of the waveform channel should be a pandas Series. Why? Because it comes with so many methods that might be useful; and it has even more plotting capabilities. At present I feel this would be overkill, and would also add another rather large dependency.

Finally, researchers often want to import and process data, then save the data at this intermediate step. This means that the next time I sit down to explore my data, I won't have to import and process all the trials from all the subjects again. I am not sure how I would achieve this, and whether it is essential. I was thinking that I could export Trial data (which would include channel data) to JSON in a way that would allow a user to read back in the JSON file and reconstitute the Trial (for the waveform channels, I might only save .values; not any of the .proc_<> version of the data that were generated at the various signal processing steps). This is likely confusing, so might be something we chat about on one of our calls.

Finally, there might be a bit more to do with plotting.

1. A simple thing would be to add an input option for the .plot methods that would save the figure to the same folder where the data was read (or a user specified folder) and then close the figure. This is handy when doing batch processing.
2. Even more useful would be to have a Trial plot, where each channel from a trial is plotted on the same figure, in individual subplots. I worked on this for a bit earlier this week, but got a bit confused how I would tackle this. This too would be a great help as it is something I do for each trial of every study I ever do...

**Comment by bbelderbos** [comment]
Great reflections. 
We can discuss testing for sure. 
For persistence what if you store results in an sqlite DB or use SQLAlchemy?
How can I help with plotting?
Bob

**Comment by MartinHeroux** [comment]
I have not really dealt with databases, so at present they seem a little too hard. But I just head a django podcast with a very great guest who was leaving their job from Oracle, and might be rather good at databases...  :)

I am open to considering it, but I might be overkill for an MVP.

For plotting I think I will now be able to tackle it...I think I tried to figure it out before I had finished the Trial class and had all the channel classes (and the mixin) finished. 

So for the next week I think there will be some focus on testing and plotting (and maybe some database stuff). Then we might reassess where we things are at and determine what would be the most useful. 

I definitely want to tackle the open source  stuff:

- Improve inline documentation with examples, etc and having a way to automate Sphinx 
    - or whatever way works well and you can help me with
    - on that note, I would beinterested in hearing your opinion on documentation that includes codes examples, description, compared to having separate .rst files
- Then there is the various words I hear about:
    - wheels, travis, continuous integration, pypi, tox, black, etc.
    - mypi? As you can see from my current code it still does not come natural to me to include type hints. It seems to be a 'thing', but I have not yet figured out how to use it regularly. Is this something worth putting effort into? Or should I leave it as something to do in my own time, once my PDM time is done?

Enough babbling for now. Chat soon.

**Comment by bbelderbos** [comment]
mypy is a nice-to-have but as typing is not reenforced you could wonder how useful it is. I guess it depends the project. 

I would focus on documentation (Sphinx), tox + CI (run your tests automatically upon every push to github), packaging (upload to pypi) and possibly some pre-commit hooks to run flake and/ or black.

Regarding Sphinx, seems you used it last time, no? Main concern here is how to automate the build of rst > html output files?

**Comment by bbelderbos** [comment]
For caching objects, check out the `pickle` module - https://stackoverflow.com/a/4529901

**Comment by MartinHeroux** [comment]
I did use Sphinx and I liked the experience, but did not having anything automated. 

So that is the biggest thing to focus on, possibly with some pre-commit hooks for flake/black.

**Comment by MartinHeroux** [comment]
Pickles and dill...I went looking for 'cornichon', but alas, no. 

I will try pickle, but it seems dill my might what I am looking for. I will give them both a try and report back.

**Comment by bbelderbos** [comment]
Cool, have not heard about `dill`, looking forward to it!

**Pull request merged**
