### PR TITLE
Added tests for read.py module

### PR DESCRIPTION
**Pull request by MartinHeroux**
As you will see, I could not get on of my tests to run: it is the one that is commented it out.

Could you have a look and see what I am doing wrong. 

Thanks.

p.s. I have created a github 'Project' to track these issues and pull-requests.

### CODE REVIEW

**Comment by bbelderbos** [comment]
How do you run your tests? I get `E   ModuleNotFoundError: No module named 'read'`

**Comment by bbelderbos** [comment]
Fixed the imports to have `pytest` work from the project root dir / also fixed the commented test, see https://github.com/MartinHeroux/spike2py/pull/10 > commit messages

**Comment by MartinHeroux** [comment]
> How do you run your tests? I get `E ModuleNotFoundError: No module named 'read'`

I was running them via Pycharm, which is likely the problem. I will look at how you fixed the issue and make sure I follow that style in future.

Thanks.

**Comment by bbelderbos** [comment]
OK good to know thanks. So you will look into adding a conftest right?

I pulled master and I got `8 failed, 10 passed, 2 warnings in 2.71s` - are you working on something that causes it to break?

**Comment by MartinHeroux** [comment]
I fixed the various breaking tests: all 18 tests pass now. 

After doing some of the pytest path bites I think I will add a few permutations so ensure I cover most cases. I will add this as an issue.

**Comment by bbelderbos** [comment]
Cool, great work. Don't do too many Bites for now, you have lifetime access to the platform so that part is not bound to time.

Also `mutpy` can be a b* and I don't use it much in practice, because it's a tool that can easily go into nit-picking (the 20 of the 80/20). 

Your tests are probably good enough for now. I rather have you keep developing the main code.

**Comment by MartinHeroux** [comment]
Sounds good. I just remember reading in the onboarding stuff that you encouraged PDM mentees to do some bites every week. 

I will focus on my code and get to the bites after the PDM program is done.

**Pull request merged**
