### PR TITLE
Fix test read

### PR DESCRIPTION
**Pull request by MartinHeroux**
1. Made changes to read.py module and test_read.py to fix all the failing tests. I clearly had not done a good job of running and checking my tests. I won't be running my tests via Pycharm any more.

One question, what is more pythonic?

```python
units_flattened = _flatten(mat_waveform['units'])
units = None
if len(units_flattened) != 0:
    units = units_flattened[0]
```
or 
```python
try:
    _flatten(mat_waveform['units'])[0]
except IndexError:
    units = None
```

I used to top example because this is how I dealt with checking whether there was actually any `keyboard` data; but I now realise I could have used a `try` `except` pattern there as well. Which is more pythonic and informative?

2. I will look into conftest.py and add one once I learn what should be in such a file.

3. Apologies for the mess that was my code and tests. Clearly working on multiple branches, make (and accepting) merge requests, etc is not something I have lots of experience with. I made changes to Master after requesting to merge my testing branch; not good. I guess I am not sure how to go about fixing typos or small changes that are not part of a major theme; do they deserve their own branch? Do I include/hide them in another branch, the one I am working on at the time (but that is not focused on the code where I fixed the typo or made a slight change)? Still getting use to working so carefully with git; this is good practice.

### CODE REVIEW

**Comment by bbelderbos** [comment]
"clearly had not done a good job" / "Apologies for the mess that was my code and tests" / "not good" - please watch your self talk ;)

Let me set this straight: you are doing a tremendous job at what you have committed so far and how coachable you are, hats off.

**Comment by bbelderbos** [comment]
No need for `len(units_flattened) != 0:` because an empty list is already "falsy" so I would code this as `units = units_flattened[0] if units_flattened else None`

**Comment by MartinHeroux** [comment]
I made the suggested change and I got the following warning. So I decided to implement their suggestion.

warning

**Comment by bbelderbos** [comment]
Sounds good

**Comment by bbelderbos** [comment]
Interestingly posting this ternary variable assignment [on Twitter](https://twitter.com/pybites/status/1291280010158850048) today, some disadvantages were mentioned:
- coverage won't "see" it
- less "Explicit is better than implicit" (zen of Python)
- might lead to PEP8 violations (E501: line too long error)

I still like it for this specific scenario but I want to make sure you are aware of these and decide for yourself ...

**Pull request merged**
